---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/18 13:49
---

--[=================[
智能施法系统
]=================]

local jass = require "jass.common"
local slk = require "jass.slk"
local japi = require "jass.japi"

-- 目标允许的FLAG
local FLAG = {
    ["地面"] = 1 << 1,
    ["空中"] = 1 << 2,
    ["建筑"] = 1 << 3,
    ["守卫"] = 1 << 4,
    ["物品"] = 1 << 5,
    ["树木"] = 1 << 6,
    ["墙"] = 1 << 7,
    ["残骸"] = 1 << 8,
    ["装饰物"] = 1 << 9,
    ["桥"] = 1 << 10,
    ["位置"] = 1 << 11,
    ["自己"] = 1 << 12,
    ["玩家单位"] = 1 << 13,
    ["联盟"] = 1 << 14,
    ["中立"] = 1 << 15,
    ["敌人"] = 1 << 16,
    ["未知"] = 1 << 17,
    ["未知"] = 1 << 18,
    ["未知"] = 1 << 19,
    ["可攻击的"] = 1 << 20,
    ["无敌"] = 1 << 21,
    ["英雄"] = 1 << 22,
    ["非-英雄"] = 1 << 23,
    ["存活"] = 1 << 24,
    ["死亡"] = 1 << 25,
    ["有机生物"] = 1 << 26,
    ["机械类"] = 1 << 27,
    ["非-自爆工兵"] = 1 << 28,
    ["自爆工兵"] = 1 << 29,
    ["非-古树"] = 1 << 30,
    ["古树"] = 1 << 31,
}

FLAG["敌我判断"] = FLAG["自己"] | FLAG["玩家单位"] | FLAG["联盟"] | FLAG["中立"] | FLAG["敌人"]

-- 判断单位是否符合技能的目标允许
local function target_filter(u, unit, flag, slk)
    local player = jass.GetOwningPlayer(u)
    -- 可见
    if jass.IsUnitInvisible(unit, player) then
        return false
    end
    -- 存活
    if flag & FLAG["死亡"] == 0 and jass.IsUnitType(unit, jass.UNIT_TYPE_DEAD) then
        return false
    end
    -- 无敌
    if flag & FLAG["无敌"] == 0 and jass.GetUnitAbilityLevel(unit, 1098282348 --[['Avul']]) == 1 then
        return false
    end
    -- 魔免
    if (not tonumber(slk.reqLevel) or tonumber(slk.reqLevel) <= 1) and jass.IsUnitType(unit, jass.UNIT_TYPE_MAGIC_IMMUNE) then
        return false
    end
    if flag & FLAG["敌我判断"] ~= 0 then
        -- 敌人
        if flag & FLAG["敌人"] == 0 and jass.IsUnitEnemy(unit, player) then
            return false
        end
        -- 自己
        if flag & FLAG["自己"] == 0 and unit == u then
            return false
        end
        -- 玩家单位
        if flag & FLAG["玩家单位"] == 0 and jass.GetOwningPlayer(unit) == player then
            return false
        end
        -- 联盟
        if flag & FLAG["联盟"] == 0 and jass.IsUnitAlly(unit, player) then
            return false
        end
    end
    -- 非英雄
    if flag & FLAG["非-英雄"] ~= 0 and jass.IsHeroUnitId(unit) then
        return false
    end
    -- 英雄
    if flag & FLAG["英雄"] ~= 0 and not jass.IsHeroUnitId(unit) then
        return false
    end
    -- 更多筛选请自己定义
    return true
end

-- 从鼠标位置处找出一个单位
local jass_group = jass.CreateGroup()
local function find_target(u, ability)
    -- 读取技能的目标类型
    local data = slk.ability[ability]
    if not data then
        return nil
    end
    local level = jass.GetUnitAbilityLevel(u, ability)
    -- 取出技能的目标类型
    local target_type = japi.EXGetAbilityDataInteger(japi.EXGetUnitAbility(u, ability), level, 0x64)
    local group = {}
    -- 选取单位组
    jass.GroupEnumUnitsInRange(jass_group, x, y, 800, nil)
    while true do
        local unit = jass.FirstOfGroup(jass_group)
        if not unit then
            break
        end
        -- 判断是否符合目标允许
        if target_filter(u, unit, target_type, data) then
            table.insert(group, unit)
        end
        jass.GroupRemoveUnit(jass_group, unit)
    end
    -- 排序,找出最接近的那个单位
    table.sort(group, function(u1, u2)
        -- 英雄比非英雄优先
        local h1 = jass.IsHeroUnitId(u1)
        local h2 = jass.IsHeroUnitId(u2)
        if h1 and not h2 then
            -- 返回true表示u1排在u2前面
            return true
        end
        if h2 and not h1 then
            -- 返回false表示u2排在u1前面
            return false
        end
        -- 距离越近越优先
        local x1 = jass.GetUnitX(u1)
        local y1 = jass.GetUnitY(u1)
        local x2 = jass.GetUnitX(u2)
        local y2 = jass.GetUnitY(u2)
        return (x1 - x) * (x1 - x) + (y1 - y) * (y1 - y) < (x2 - x) * (x2 - x) + (y2 - y) * (y2 - y)
    end)
    -- 返回单位组里的第一个单位
    return group[1]
end




-- 立即发动技能
--- @param u unit
--- @param ability number
--- @param order number
--- @param target_type number
local function cast_ability(u, ability, order, target_type)
    local target = find_target(u, ability)
    -- 点目标命令或单位目标命令
    if not target then
        return
    end
    if (target_type == 2 or target_type == 4) then
        u:issue_order(order, target)
    elseif target_type == 1 then
        -- 无目标命令
        u:issue_order(order)
    end
end

et.loop(300, function()
    for u, t in pairs(et.tower.all_towers) do
        for _, ability in ipairs(t.ability_list) do
            local ability_id = base.string2id(ability)
            local order = ORDER_LOOKUP[ability]
            local level = jass.GetUnitAbilityLevel(u, ability)
            -- 取出技能的目标类型
            local target_type = japi.EXGetAbilityDataInteger(japi.EXGetUnitAbility(u, ability), level, 0x64)
            cast_ability(u, ability, order, target_type)
        end
    end
end)
