---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 14:13
---

--------------------------
--- 处理杀怪奖励
--------------------------
local g = require 'jass.globals'

--- 杀怪加声望
---@param killer unit
---@param killed unit
et.game:event '单位-死亡'(function(self, killer, killed)
    -- TODO 杀小兵和英雄加的声望数不同
    if killed:get_owner() == ATTACKER_PLAYER then
        if et.tower.all_towers[killer] then
            --- @type tower
            local tower = et.tower.all_towers[killer]
            tower.reputation = tower.reputation + 1
        end
        local gold = g.wave * 2 + base.random_int(0, 2) + base.random_int(0, 2)
        killer:get_owner():add_gold(gold)
        et.tag.create(('+%s'):format(gold), killed:get_point(), 11, 0, 80, 50, 20, 30, 0.65, 400, base.random(80, 100))
    end
end)