---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 11:16
---

--- 查看当前属性
--- @param u unit
--- @param id number
--- @param target unit | item | point
et.game:event '单位-技能生效' (function (self, u, id, target)
    if id == base.string2id('A04P') then
        local p = u:get_owner()
        p:send_message(('当前福缘：%s'):format(p.luck))
    end
end)