---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/15 14:05
---

boards = {} -- 积分板
-- TODO 修改为multiboard并将其修改为随时更新
-- 显示积分板
for i = 1, 4 do
    boards[i] = CreateLeaderboard()
    LeaderboardSetLabel(boards[i], "剩余生命点")
    PlayerSetLeaderboard(Player(i - 1), boards[i])
    LeaderboardDisplay(boards[i], true)
    LeaderboardAddItemBJ(Player(i - 1), boards[i], "圈内敌人", 100)
end

--- 当圈内敌人大于指定数值时失败
et.loop(10 * 1000, function()
    --- @param u unit
    local filter = function(u)
        return u:get_owner() == ATTACKER_PLAYER and u:is_alive()
    end
    local count = GAME_AREA:get_unit_count(filter)
    log.debug(('当前圈内敌人数为%s'):format(count))
    if count >= FAIL_COUNT then
        -- force.send_message("|CFFFF00B2决战江湖1.55的游戏总评分：" .. ae .. "分（战败）")
        force.fail()
    end
end)