---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 10:21
---

--- 使用大礼包获得相应奖励
--- @param u unit
--- @param it item
et.game:event '单位-使用物品'(function(self, u, it)
    if (it:get_id() == base.string2id('I039')) then
        -- 完美的武魂石
        local item = u:add_item('I022')
        u:get_owner():send_message('打开新手大礼包，获得金钱+2000，获得物品：' .. item:get_name())
    end
end)