---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/12 14:25
---

--- 塔表
towers = {}

towers.junior = {} -- 初级塔
towers.intermediate = {} -- 中级塔
towers.senior = {} -- 高级塔
towers.hero = {} -- 英雄塔

--- 玩家常量
ATTACKER_PLAYER = jass.Player(5)

--- 物品等级表
--- @type table<string, number>
ITEM_LOOKUP = {
    AAAA = 1
}