---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/18 19:09
---

-- 丐帮心法

--- @param u unit
--- @param id number
--- @param target unit|item|point
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == base.string2id('A031') then
        if u:is_hero() then
            u:set_mana(u:get_mana() + 50)
        else
            target:set_lifetime(1)
            jass.UnitDamageTarget(u.handle, target.handle, 10000000, true, false, jass.ATTACK_TYPE_CHAOS, jass.DAMAGE_TYPE_MAGIC, jass.WEAPON_TYPE_WHOKNOWS)
            target:remove()
            local bonus = target:get_max_life() * 0.05 * u:get_ability_level(id)
            u:add_bonus(BONUS_TYPE.ATTACK, bonus)
            et.wait(5000, function()
                u:add_bonus(BONUS_TYPE.ATTACK, -bonus)
            end)
        end
    end
end)


