---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/18 20:59
---

--丐帮身法
--- @param source unit 攻击方
--- @param target unit 受攻击方
et.game:event '单位-受攻击'(function(self, source, target)
    local p = source:get_owner()
    base.triggerPassive({
        attacker = source,
        attacked = target,
        spell_id = 'A037',
        shadow_id = 'A036',
        order_id = 0xD0085,
        possibility = p.luck / 50 + 5 + source:get_ability_level('A037') * 3,
        mana_cost = 30
    })
end)