---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/18 16:54
---

--铜锤手

--- @param u unit
--- @param id string
--- @param target unit|item|point|nil
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 'A02R' then
        base.dummy_issue_order({
            producer = u,
            target = target,
            ability_id = 'A02S',
            order_id = ORDER_LOOKUP['A02S'],
            ability_level = u:get_ability_level(id)
        })
    end
end)

--- 铜锤手伤害
--- @param source unit
--- @param target unit
--- @param damage number
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if base.float_equal(damage, 0.13) then
        local real_damage = base.damageFormula(source, target, 'A02R', 500)
        base.apply_damage(source, target, real_damage)
    end
end)