---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 13:51
---

--- 丐帮武学

--- 丐帮帮规
--  每100点声望增加所有丐帮武学10%的伤害

-- 太祖棍法
require 'kungfu.beggar.taizuStick'

-- 太祖拳法
require 'kungfu.beggar.taizuFist'

-- 丐帮入门棍法
require 'kungfu.beggar.newbeeStick'

-- 铜锤手
require 'kungfu.beggar.copperHammer'

--疯魔杖法
require 'kungfu.beggar.crazyWand'

--逍遥游
require 'kungfu.beggar.happyExcursion'

--丐帮心法
require 'kungfu.beggar.beggarCitta'

--降龙十八掌
require 'kungfu.beggar.yieldDragon'

--打狗棒法
require 'kungfu.beggar.beatDog'

--丐帮身法
require 'kungfu.beggar.beggarBody'

--莲花掌
require 'kungfu.beggar.lotusPalm'

-- 青竹镖
require 'kungfu.beggar.bambooDart'

--六合刀法
require 'kungfu.beggar.markSixKnife'



