---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 13:51
---

--- 丐帮武学

--- 丐帮帮规
--  每100点声望增加所有丐帮武学10%的伤害

-- 太祖棍法
require 'kungfu.beggar.taizuStick'

-- 太祖拳法
require 'kungfu.beggar.taizuFist'

-- 丐帮入门棍法
require 'kungfu.beggar.newbeeStick'

-- 铜锤手
require 'kungfu.beggar.copperHammer'

--疯魔杖法
require 'kungfu.beggar.crazyWand'

--逍遥游
require 'kungfu.beggar.happyExcursion'

--丐帮心法


--降龙十八掌
--打狗棒法
--丐帮身法
--莲花掌
--青竹镖
--六合刀法

