---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/18 16:32
---

--丐帮入门棍法
--- @param source unit
--- @param target unit
et.game:event '单位-受攻击'(function(self, source, target)

    base.passiveRangeDamage({
        attacker = source,
        attacked = target,
        spell_id = 'A02K',
        range = 400,
        effect = "Abilities\\Spells\\Undead\\AnimateDead\\AnimateDeadTarget.mdl",
        possibility = source:get_owner().luck / 50 + 18,
        mana_cost = 15
    })

end)