---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/18 16:07
---

--太祖长拳
--- 太祖长拳伤害
--- @param source unit
--- @param target unit
--- @param damage number
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if base.float_equal(damage, 0.12) then
        local real_damage = base.damageFormula(source, target, 'A02I')
        base.apply_damage(source, target, real_damage)
    end
end)