---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/11 19:47
---

local jass = require 'jass.common'
local tower = {}

---@class tower
local mt = {}
tower.__index = mt

--- @type j_unit
mt.handle = 0

function tower:__tostring()
    return ('%s'):format(self.id)
end


--- 创建塔
--- @param u j_unit
--- @return tower
function tower.create(u)
    local t = setmetatable({}, tower)
    t.handle = u
    return t
end